import type { CollectionConfig } from 'payload'

export const Treatments: CollectionConfig = {
  slug: 'treatments',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'slug', 'category', 'updatedAt'],
    group: 'Catalog',
  },
  access: { read: () => true },
  fields: [
    { name: 'name', type: 'text', required: true, index: true },
    { name: 'slug', type: 'text', required: true, unique: true, index: true },
    {
      name: 'category',
      type: 'select',
      required: true,
      options: [
        { label: 'Neurotoxin', value: 'neurotoxin' },
        { label: 'Filler', value: 'filler' },
        { label: 'Biostimulator', value: 'biostimulator' },
        { label: 'Skin', value: 'skin' },
        { label: 'Thread', value: 'thread' },
        { label: 'Body', value: 'body' },
        { label: 'Other', value: 'other' },
      ],
    },
    { name: 'tagline', type: 'text', maxLength: 100 },
    { name: 'shortDescription', type: 'textarea' },
    {
      name: 'bodyAreas',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'Forehead',    value: 'forehead' },
        { label: 'Brow',        value: 'brow' },
        { label: 'Under Eye',   value: 'under-eye' },
        { label: "Crow's Feet", value: 'crows-feet' },
        { label: 'Cheeks',      value: 'cheeks' },
        { label: 'Lips',        value: 'lips' },
        { label: 'Chin',        value: 'chin' },
        { label: 'Jawline',     value: 'jawline' },
        { label: 'Neck',        value: 'neck' },
        { label: 'Décolletage', value: 'decolletage' },
      ],
    },
    { name: 'avgPriceFromUsd', type: 'number' },
    { name: 'avgPriceToUsd', type: 'number' },
    { name: 'priceUnit', type: 'select', options: [
      { label: 'Per unit', value: 'per_unit' },
      { label: 'Per session', value: 'per_session' },
      { label: 'Per syringe', value: 'per_syringe' },
    ]},
    { name: 'iconSlug', type: 'text', admin: { description: 'Phosphor icon slug.' } },
    {
      name: 'painIndex',
      type: 'number',
      min: 0,
      max: 10,
      admin: { description: 'Typical patient pain level 0 (none) to 10 (severe).' },
    },
    {
      name: 'longevityLabel',
      type: 'text',
      admin: { description: 'e.g. "3 to 4 months" or "Permanent"' },
    },
    { name: 'longevityMonthsMin', type: 'number', admin: { description: 'Minimum longevity in months (0 for permanent).' } },
    { name: 'longevityMonthsMax', type: 'number', admin: { description: 'Maximum longevity in months (0 for permanent).' } },
    {
      name: 'downtimeLabel',
      type: 'text',
      admin: { description: 'e.g. "0 to 24 hours" or "14 to 28 days"' },
    },
    { name: 'downtimeHoursMax', type: 'number', admin: { description: 'Maximum downtime in hours.' } },
    {
      name: 'guide',
      type: 'relationship',
      relationTo: 'guides',
      admin: { description: 'Pillar guide for this treatment.' },
    },
  ],
  timestamps: true,
}
