/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    treatments: Treatment;
    locations: Location;
    brands: Brand;
    clinics: Clinic;
    providers: Provider;
    reviews: Review;
    photos: Photo;
    qa: Qa;
    authors: Author;
    'medical-reviewers': MedicalReviewer;
    guides: Guide;
    news: News;
    faqs: Faq;
    'before-after-cases': BeforeAfterCase;
    bookings: Booking;
    promotions: Promotion;
    'audit-logs': AuditLog;
    'data-alerts': DataAlert;
    claims: Claim;
    subscribers: Subscriber;
    'zip-codes': ZipCode;
    'video-testimonials': VideoTestimonial;
    'social-posts': SocialPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    treatments: TreatmentsSelect<false> | TreatmentsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    clinics: ClinicsSelect<false> | ClinicsSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    qa: QaSelect<false> | QaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'medical-reviewers': MedicalReviewersSelect<false> | MedicalReviewersSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'before-after-cases': BeforeAfterCasesSelect<false> | BeforeAfterCasesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'data-alerts': DataAlertsSelect<false> | DataAlertsSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'zip-codes': ZipCodesSelect<false> | ZipCodesSelect<true>;
    'video-testimonials': VideoTestimonialsSelect<false> | VideoTestimonialsSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Staff, provider, and patient accounts. Role controls access; only admins and editors can change a role.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor' | 'provider' | 'patient' | 'clinic' | 'brand') | null;
  /**
   * Set on claim approval. The provider profile this user can edit.
   */
  linkedProvider?: (number | null) | Provider;
  /**
   * Set on claim approval. The clinic profile this user can edit.
   */
  linkedClinic?: (number | null) | Clinic;
  /**
   * Set on claim approval. The brand this user can manage.
   */
  linkedBrand?: (number | null) | Brand;
  /**
   * Providers this patient saved from the directory. Editable by the patient on /profile.
   */
  savedProviders?: (number | Provider)[] | null;
  /**
   * Clinics this patient saved from the directory. Editable by the patient on /profile.
   */
  savedClinics?: (number | Clinic)[] | null;
  /**
   * Treatment slug saved from the candidate quiz, surfaced as "recommended for you" on /profile. Not medical advice.
   */
  quizRecommendation?: string | null;
  setupToken?: string | null;
  setupTokenExpiry?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Individual injectors. Ratings come from imported reviews and are read-only. Verification and ratings cannot be set by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  providerId: string;
  fullName: string;
  slug: string;
  credentials: 'MD' | 'DO' | 'NP' | 'PA' | 'RN' | 'DDS';
  title: string;
  yearsExperience?: number | null;
  yearStartedPracticing?: number | null;
  /**
   * Primary location.
   */
  clinic: number | Clinic;
  /**
   * Other locations (branches) where this provider also practices, beyond the primary "clinic" above. Shown as "Also practices at" on the public profile. Optional. A claimed owner can also manage these from their dashboard.
   */
  additionalClinics?: (number | Clinic)[] | null;
  boardCertifications?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  licenseNumber: string;
  licenseState: string;
  licenseStatus: 'Active' | 'Inactive' | 'Expired';
  licenseVerificationUrl: string;
  npiNumber?: string | null;
  tagline?: string | null;
  bio?: string | null;
  profilePhotoUrl?: string | null;
  /**
   * Uploaded headshot. When set, this is shown instead of the legacy profilePhotoUrl. A claimed provider can upload this from their dashboard.
   */
  profilePhoto?: (number | null) | Media;
  languages?:
    | (
        | 'English'
        | 'Spanish'
        | 'Mandarin'
        | 'Korean'
        | 'Hindi'
        | 'Russian'
        | 'French'
        | 'Portuguese'
        | 'Arabic'
        | 'Vietnamese'
      )[]
    | null;
  gender?: ('Female' | 'Male' | 'Non-binary' | 'Unknown') | null;
  treatmentsOffered: (number | Treatment)[];
  specialties?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  pricingBotoxPerUnit?: number | null;
  pricingFillerPerSyringe?: number | null;
  pricingConsultation?: number | null;
  /**
   * Display price on cards.
   */
  startingPrice?: number | null;
  /**
   * Loyalty programs accepted at this practice.
   */
  loyaltyPrograms?: ('alle' | 'aspire' | 'xperience' | 'other')[] | null;
  acceptsNewPatients?: boolean | null;
  offersVirtualConsult?: boolean | null;
  offersInPerson?: boolean | null;
  websiteUrl?: string | null;
  email?: string | null;
  phoneDirect?: string | null;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  linkedinUrl?: string | null;
  /**
   * Computed from imported reviews. Not hand-editable (trust signal).
   */
  aggregateRating?: number | null;
  /**
   * Number of reviews behind the rating. Set by import.
   */
  aggregateRatingCount?: number | null;
  /**
   * Show "Top Pick" ribbon on homepage.
   */
  editorsPick?: boolean | null;
  featuredRank?: number | null;
  /**
   * Plan tier for this provider. Controls feature gating on the public profile and dashboard.
   */
  subscriptionTier?: ('free' | 'starter' | 'pro' | 'elite') | null;
  /**
   * Billing status. Set manually for now (manual billing v1); Stripe self-serve later.
   */
  subscriptionStatus?: ('none' | 'active' | 'past_due' | 'canceled') | null;
  sourceUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  lastScrapedDate?: string | null;
  /**
   * Set by the data importer to group a batch (for scoped re-import / wipe). Not hand-editable.
   */
  importBatch?: string | null;
  /**
   * Set automatically when a claim is approved. Not hand-editable.
   */
  claimed?: boolean | null;
  /**
   * The user who claimed this profile. Set on claim approval.
   */
  claimedBy?: (number | null) | User;
  status: 'published' | 'review' | 'draft';
  /**
   * Total profile page views (server-side, bot-filtered). Auto-incremented, not hand-editable.
   */
  profileViewCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Physical clinic locations. Ratings come from imported reviews and are read-only. Each clinic is its own page and location.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics".
 */
export interface Clinic {
  id: number;
  clinicId: string;
  clinicName: string;
  slug: string;
  tagline?: string | null;
  description?: string | null;
  clinicType?: ('medspa' | 'dermatology' | 'plastic-surgery' | 'dental-aesthetics' | 'other') | null;
  /**
   * Parent brand, if this clinic is one of several branches. Optional. Each clinic stays its own location.
   */
  brand?: (number | null) | Brand;
  addressLine1: string;
  addressLine2?: string | null;
  city: string;
  state: string;
  zip: string;
  neighborhood?: string | null;
  county?: string | null;
  country: string;
  latitude: number;
  longitude: number;
  googlePlaceId?: string | null;
  googleMapsUrl?: string | null;
  directionsUrl?: string | null;
  appleMapsUrl?: string | null;
  phone: string;
  email?: string | null;
  websiteUrl: string;
  bookingUrl?: string | null;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  facebookUrl?: string | null;
  hoursJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  serviceType: 'In-Person' | 'Telehealth' | 'Both';
  treatmentsOffered?: (number | Treatment)[] | null;
  offersVirtualConsult?: boolean | null;
  acceptsNewPatients?: boolean | null;
  /**
   * Lowest service price shown on listing cards.
   */
  startingPrice?: number | null;
  languages?: ('en' | 'es' | 'fr' | 'zh' | 'yue' | 'ko' | 'pt' | 'ar' | 'hi' | 'ru')[] | null;
  acceptsInsurance?: boolean | null;
  /**
   * Semicolon list.
   */
  paymentMethods?: string | null;
  /**
   * Semicolon list.
   */
  amenities?: string | null;
  logoUrl?: string | null;
  clinicPhotoUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Uploaded clinic photos (gallery). When set, these are shown instead of the legacy clinicPhotoUrls. A claimed clinic owner can upload these from their dashboard.
   */
  photos?: (number | Media)[] | null;
  /**
   * Computed from imported reviews. Not hand-editable (trust signal).
   */
  aggregateRating?: number | null;
  /**
   * Number of reviews behind the rating. Set by import.
   */
  aggregateRatingCount?: number | null;
  providers?: (number | Provider)[] | null;
  yearEstablished?: number | null;
  sourceUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  lastScrapedDate?: string | null;
  /**
   * Set by the data importer to group a batch (for scoped re-import / wipe). Not hand-editable.
   */
  importBatch?: string | null;
  /**
   * Plan tier for this clinic. Entitlement for clinic-level features derives from the claimed-owner provider's tier.
   */
  subscriptionTier?: ('free' | 'starter' | 'pro' | 'elite') | null;
  /**
   * Billing status. Set manually for now (manual billing v1); Stripe self-serve later.
   */
  subscriptionStatus?: ('none' | 'active' | 'past_due' | 'canceled') | null;
  /**
   * Set automatically when a claim is approved. Not hand-editable.
   */
  claimed?: boolean | null;
  /**
   * The user who claimed this profile. Set on claim approval.
   */
  claimedBy?: (number | null) | User;
  status: 'published' | 'review' | 'draft';
  /**
   * Scraper confidence score. 100 = fully verified.
   */
  dataConfidence?: number | null;
  /**
   * Flag set by importer when data looks uncertain.
   */
  needsManualReview?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A parent company that groups one or more clinic locations (branches). Each clinic stays its own location with its own page; the brand only groups them. Brand hubs render at /brands/[slug]. Brands are created from the admin dashboard branch-suggestion tool (or by hand here); branch detection only suggests, it never merges automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  brandId: string;
  name: string;
  slug: string;
  logoUrl?: string | null;
  websiteUrl?: string | null;
  description?: string | null;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  linkedinUrl?: string | null;
  /**
   * Plan tier for this brand. Elite required for multi-location / brand management features.
   */
  subscriptionTier?: ('free' | 'starter' | 'pro' | 'elite') | null;
  /**
   * Billing status. Set manually for now (manual billing v1); Stripe self-serve later.
   */
  subscriptionStatus?: ('none' | 'active' | 'past_due' | 'canceled') | null;
  /**
   * Set automatically when a claim is approved. Not hand-editable.
   */
  claimed?: boolean | null;
  /**
   * The user who claimed this brand. Set on claim approval.
   */
  claimedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * The master treatment list. Providers and guides link to these. Changing a slug changes its public URL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments".
 */
export interface Treatment {
  id: number;
  name: string;
  slug: string;
  category: 'neurotoxin' | 'filler' | 'biostimulator' | 'skin' | 'thread' | 'body' | 'other';
  tagline?: string | null;
  shortDescription?: string | null;
  bodyAreas?:
    | (
        | 'forehead'
        | 'brow'
        | 'under-eye'
        | 'crows-feet'
        | 'cheeks'
        | 'lips'
        | 'chin'
        | 'jawline'
        | 'neck'
        | 'decolletage'
      )[]
    | null;
  avgPriceFromUsd?: number | null;
  avgPriceToUsd?: number | null;
  priceUnit?: ('per_unit' | 'per_session' | 'per_syringe') | null;
  /**
   * Phosphor icon slug.
   */
  iconSlug?: string | null;
  /**
   * Typical patient pain level 0 (none) to 10 (severe).
   */
  painIndex?: number | null;
  /**
   * e.g. "3 to 4 months" or "Permanent"
   */
  longevityLabel?: string | null;
  /**
   * Minimum longevity in months (0 for permanent).
   */
  longevityMonthsMin?: number | null;
  /**
   * Maximum longevity in months (0 for permanent).
   */
  longevityMonthsMax?: number | null;
  /**
   * e.g. "0 to 24 hours" or "14 to 28 days"
   */
  downtimeLabel?: string | null;
  /**
   * Maximum downtime in hours.
   */
  downtimeHoursMax?: number | null;
  /**
   * Pillar guide for this treatment.
   */
  guide?: (number | null) | Guide;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form treatment guides and articles. Search engine title and description are in the Meta tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  slug: string;
  /**
   * Hero subhead, 1 to 2 sentences.
   */
  lede: string;
  /**
   * Short summary for listing cards and search snippets (under 200 characters). Also used as the default meta description.
   */
  excerpt?: string | null;
  /**
   * Upload the cover image directly. Drag and drop a file or pick from the media library.
   */
  coverImage?: (number | null) | Media;
  /**
   * Legacy / external cover image URL. Used only if no cover image is uploaded above.
   */
  coverImageUrl?: string | null;
  category: 'treatment-guide' | 'article' | 'expert-qa' | 'cost-report';
  relatedTreatment?: (number | null) | Treatment;
  readTimeMin?: number | null;
  sourcesCount?: number | null;
  author: number | Author;
  medicalReviewer?: (number | null) | MedicalReviewer;
  lastMedicallyReviewed?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 40-80 word answer-first summary shown at the top of the guide for featured snippets.
   */
  answerSnippet?: string | null;
  /**
   * Array of short facts, e.g. ["Fact 1", "Fact 2"]. Rendered as a bullet list above the body.
   */
  atAGlance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Inline array of {question, answer} for imported FAQ content. Shown alongside the existing faqs relationship.
   */
  faq?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {title, publisher, url, publishedDate, sourceType, claimsSupported[]} objects. Rendered as a citations block.
   */
  sources?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  faqs?: (number | Faq)[] | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Gate: only Approved guides are visible to the public. Use the Approve API or admin bulk action to approve.
   */
  reviewStatus: 'imported' | 'in-review' | 'approved';
  /**
   * Use "Index next N" in the admin cockpit to drip approved guides into Google gradually.
   */
  indexState: 'noindex' | 'indexed';
  /**
   * When checked, the page emits nofollow in its robots meta tag. Cleared automatically when drip-indexed.
   */
  nofollow?: boolean | null;
  /**
   * Stamped by the content importer. Use to identify which batch this item came from.
   */
  importBatch?: string | null;
  /**
   * Set automatically when approved.
   */
  approvedAt?: string | null;
  /**
   * Set automatically when approved.
   */
  approvedBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload images here. Drag and drop, or click to browse.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Required.
   */
  alt: string;
  /**
   * Optional caption shown beneath the image in articles.
   */
  caption?: string | null;
  /**
   * Optional photo credit or source attribution.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Editorial bylines shown on guides and articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  fullName: string;
  slug: string;
  role?: string | null;
  bio?: string | null;
  photoUrl?: string | null;
  linkedinUrl?: string | null;
  twitterUrl?: string | null;
  articleCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Board-certified reviewers credited on medically reviewed content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-reviewers".
 */
export interface MedicalReviewer {
  id: number;
  fullName: string;
  slug: string;
  credentials: 'MD' | 'DO' | 'NP' | 'PA' | 'RN' | 'DDS' | 'PhD';
  title: string;
  city?: string | null;
  state?: string | null;
  bio?: string | null;
  photoUrl?: string | null;
  npiNumber?: string | null;
  boardCertifications?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Link to provider record if they also see patients.
   */
  linkedProvider?: (number | null) | Provider;
  linkedinUrl?: string | null;
  reviewedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable FAQ entries that feed FAQ schema on the matching pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * 40 to 80 words ideal for AEO snippets.
   */
  answer: string;
  scope: 'homepage' | 'treatment' | 'city' | 'guide';
  treatmentTag?: string | null;
  cityTag?: string | null;
  /**
   * "Read the full guide" link target.
   */
  relatedGuide?: (number | null) | Guide;
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * States, metros, cities, and neighborhoods. Use the sidebar toggles to set a market live or hide it from search engines.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  kind: 'country' | 'state' | 'metro' | 'city' | 'neighborhood';
  /**
   * 2-letter state code.
   */
  state?: string | null;
  parent?: (number | null) | Location;
  latitude?: number | null;
  longitude?: number | null;
  imageUrl?: string | null;
  providerCount?: number | null;
  sortRank?: number | null;
  featured?: boolean | null;
  /**
   * ON = this state/city is a launched market (normal directory). OFF = renders as "coming soon" with a waitlist. Default OFF.
   */
  isLive?: boolean | null;
  /**
   * ON = search engines do not index this page (and it is excluded from sitemap.xml). Default ON so thin "coming soon" pages avoid an SEO penalty. Turn OFF for live markets.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Imported and submitted reviews. Provider and clinic ratings are computed from these, so deleting reviews changes the displayed ratings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  reviewId: string;
  provider?: (number | null) | Provider;
  clinic: number | Clinic;
  reviewerFirstName?: string | null;
  reviewerInitial?: string | null;
  reviewerAgeRange?: string | null;
  reviewerCity?: string | null;
  rating: number;
  reviewTitle?: string | null;
  reviewText: string;
  treatmentTag?: string | null;
  reviewDate: string;
  sourcePlatform: 'google' | 'yelp' | 'healthgrades' | 'vitals' | 'zocdoc' | 'clinic_site' | 'injectors_world';
  sourceUrl: string;
  responseFromProvider?: string | null;
  responseDate?: string | null;
  /**
   * Only check when a real provenance trail exists: the source URL has been confirmed against the platform, or the patient submitted the review directly through the account flow. Imported reviews with a sourceUrl are typically verified; all other new records start unverified. Showing a "Verified" badge without provenance is a launch-blocker (FTC / consumer-protection risk).
   */
  verified?: boolean | null;
  featured?: boolean | null;
  /**
   * Approved reviews render publicly. Reviews submitted by logged-in patients land as Pending and are hidden until a moderator approves them. Imported and seeded reviews default to Approved.
   */
  moderationStatus?: ('approved' | 'pending' | 'rejected') | null;
  /**
   * Set when a logged-in patient submitted this review through the account flow.
   */
  submittedByUser?: (number | null) | User;
  /**
   * Set by the data importer to group a batch (for scoped re-import / wipe). Not hand-editable.
   */
  importBatch?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Provider and clinic photos. Only photos with documented consent may be shown publicly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  photoId: string;
  provider?: (number | null) | Provider;
  clinic?: (number | null) | Clinic;
  treatmentTag?: string | null;
  photoUrl: string;
  type:
    | 'before'
    | 'after'
    | 'headshot'
    | 'clinic_interior'
    | 'clinic_exterior'
    | 'treatment_room'
    | 'team'
    | 'equipment';
  /**
   * Same id on a before + after pair.
   */
  pairId?: string | null;
  weeksPostTreatment?: number | null;
  caption?: string | null;
  consentDocumented?: boolean | null;
  sourcePlatform: 'clinic_site' | 'google' | 'instagram' | 'injectors_world';
  sourceUrl: string;
  /**
   * Set by the data importer to group a batch (for scoped re-import / wipe). Not hand-editable.
   */
  importBatch?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reader questions. Set status to Answered and add an answer to publish it to /questions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qa".
 */
export interface Qa {
  id: number;
  qaId: string;
  /**
   * URL slug. Auto-generated on submission.
   */
  slug?: string | null;
  status: 'new' | 'answered' | 'rejected';
  questionTitle: string;
  questionText?: string | null;
  answeredByProvider?: (number | null) | Provider;
  /**
   * Use when provider not in our DB.
   */
  answeredByName?: string | null;
  /**
   * The answer. Required before publishing.
   */
  answerText?: string | null;
  treatmentTag?: string | null;
  cityTag?: string | null;
  sourcePlatform?: ('clinic_blog' | 'forum' | 'directory' | 'injectors_world' | 'user_submission') | null;
  sourceUrl?: string | null;
  date?: string | null;
  /**
   * Email from public submission (not displayed publicly).
   */
  submitterEmail?: string | null;
  /**
   * Set by the data importer to group a batch (for scoped re-import / wipe). Not hand-editable.
   */
  importBatch?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Timely news articles: treatment updates, industry news, company announcements. Keep separate from evergreen Guides.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL-safe slug, e.g. fda-approves-new-filler. Auto-generate from title.
   */
  slug: string;
  /**
   * Short summary for listing cards, RSS feed, and newsletter sends. Under 300 characters.
   */
  excerpt: string;
  /**
   * Upload cover image. 16:9 or wider recommended. Served from R2.
   */
  coverImage?: (number | null) | Media;
  /**
   * Legacy or external cover image URL. Only used when no file is uploaded above.
   */
  coverImageUrl?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 40-80 word answer-first summary shown at the top of the article for featured snippets.
   */
  answerSnippet?: string | null;
  /**
   * Array of short facts, e.g. ["Fact 1", "Fact 2"]. Rendered as a bullet list above the body.
   */
  atAGlance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {question, answer} objects for the FAQ accordion and FAQPage JSON-LD.
   */
  faq?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {title, publisher, url, publishedDate, sourceType, claimsSupported[]} objects. Rendered as a citations block.
   */
  sources?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  category: 'treatment-update' | 'industry' | 'company' | 'announcement' | 'product-launch' | 'research' | 'regulation';
  author: number | Author;
  /**
   * Optional. Add only when the article covers clinical or safety content.
   */
  medicalReviewer?: (number | null) | MedicalReviewer;
  publishedAt?: string | null;
  /**
   * Optional. Links to a treatment pillar page from the article.
   */
  relatedTreatment?: (number | null) | Treatment;
  /**
   * Only Published articles appear on the site. Kept in sync with Review Status: approving sets this to Published.
   */
  status: 'draft' | 'published';
  /**
   * Pin this article to the top of the news index.
   */
  featured?: boolean | null;
  /**
   * Gate: only Approved articles are visible to the public. Use the Approve API or admin bulk action to approve.
   */
  reviewStatus: 'imported' | 'in-review' | 'approved';
  /**
   * Use "Index next N" in the admin cockpit to drip approved articles into Google gradually.
   */
  indexState: 'noindex' | 'indexed';
  /**
   * When checked, the page emits nofollow in its robots meta tag. Cleared automatically when drip-indexed.
   */
  nofollow?: boolean | null;
  /**
   * Stamped by the content importer. Use to identify which batch this item came from.
   */
  importBatch?: string | null;
  /**
   * Set automatically when approved.
   */
  approvedAt?: string | null;
  /**
   * Set automatically when approved.
   */
  approvedBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Before and after cases. Only cases with consent granted are shown publicly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after-cases".
 */
export interface BeforeAfterCase {
  id: number;
  caseTitle: string;
  beforePhotoUrl: string;
  afterPhotoUrl: string;
  /**
   * Botox, Lip Filler, etc.
   */
  treatmentTag: string;
  /**
   * Weeks between before and after.
   */
  weeksPost: number;
  provider?: (number | null) | Provider;
  city?: string | null;
  state?: string | null;
  patientNote?: string | null;
  consentGranted: boolean;
  featured?: boolean | null;
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Booking and lead requests from the site. Read the request, then set the status (new → confirmed → completed). Patient contact details are staff-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  patientName: string;
  patientEmail: string;
  patientPhone?: string | null;
  provider?: (number | null) | Provider;
  clinic?: (number | null) | Clinic;
  treatment?: (number | null) | Treatment;
  treatmentTag?: string | null;
  preferredDate?: string | null;
  preferredTime?: string | null;
  message?: string | null;
  consentToContact: boolean;
  status: 'new' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  source?: ('website' | 'hero_search' | 'provider_profile' | 'guide_cta' | 'lead_form') | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes by editors.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Three placement types per scope:
 *   banner — max 1 active per scope. Needs image + link.
 *   sponsored-card — max 3 per scope. Promotes a provider OR a clinic.
 *   featured-pin — max 3 per scope. Pins to top of organic list (positions 1-3).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  /**
   * Internal label e.g. "Botox Houston Q3 2026".
   */
  title: string;
  status: 'draft' | 'active' | 'paused' | 'expired';
  /**
   * Where this promotion appears on listing pages.
   */
  placement: 'banner' | 'sponsored-card' | 'featured-pin';
  /**
   * Which pages this promotion appears on.
   */
  scope: 'national' | 'treatment' | 'state' | 'city' | 'treatment+state' | 'treatment+city';
  /**
   * Required when scope includes a treatment.
   */
  treatment?: (number | null) | Treatment;
  /**
   * State location. Required when scope = state or treatment+state.
   */
  state?: (number | null) | Location;
  /**
   * City location (kind = city or metro). Required when scope = city or treatment+city.
   */
  city?: (number | null) | Location;
  /**
   * Provider to promote. Required for sponsored-card and featured-pin unless a clinic is set instead.
   */
  provider?: (number | null) | Provider;
  /**
   * Promote a clinic instead of a provider. Set this OR provider, not both.
   */
  clinic?: (number | null) | Clinic;
  /**
   * Banner image. Required for banner placement. Recommended size: 1200 × 200 px (6:1).
   */
  bannerImage?: (number | null) | Media;
  /**
   * Destination URL when the banner is clicked (opens in new tab). Required for banner.
   */
  bannerLinkUrl?: string | null;
  /**
   * Alt text for the banner image (accessibility).
   */
  bannerAltText?: string | null;
  /**
   * Display position 1, 2, or 3 within the sponsored / featured section.
   */
  featuredRank?: number | null;
  startDate?: string | null;
  /**
   * Auto-expires after this date. Leave blank for no expiry.
   */
  endDate?: string | null;
  /**
   * Internal billing / contact notes. Not shown publicly.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only history of every create, update, and delete on tracked collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete';
  collectionSlug: string;
  documentId?: string | null;
  documentTitle?: string | null;
  /**
   * Who performed the action, or "system" for automated/public writes.
   */
  userEmail?: string | null;
  userId?: string | null;
  summary?: string | null;
  /**
   * Field names that changed (updates only).
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Data integrity and operational alerts. Resolve or acknowledge each one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-alerts".
 */
export interface DataAlert {
  id: number;
  /**
   * Set by the import / scan automation so re-scans update instead of duplicating. Not hand-editable.
   */
  alertKey: string;
  type:
    | 'duplicate_clinic'
    | 'duplicate_provider'
    | 'missing_coordinates'
    | 'missing_source'
    | 'unknown_treatment'
    | 'broken_relationship'
    | 'unmatched_city'
    | 'missing_trust_field'
    | 'invalid_zip'
    | 'invalid_coordinates'
    | 'invalid_phone'
    | 'duplicate_npi'
    | 'possible_branch'
    | 'orphaned_promotion'
    | 'promo_missing_provider'
    | 'promo_missing_image'
    | 'promo_expired'
    | 'promo_scope_mismatch'
    | 'zip_feature_request'
    | 'content_missing_reviewer'
    | 'content_missing_author'
    | 'content_few_sources'
    | 'content_missing_cover'
    | 'content_validation_error'
    | 'content_duplicate_slug'
    | 'promo_expiring_soon'
    | 'promo_slot_exceeded'
    | 'other';
  severity: 'error' | 'warning' | 'info';
  message: string;
  collectionSlug?: string | null;
  /**
   * Business id (e.g. providerId / clinicId) or DB id.
   */
  documentId?: string | null;
  /**
   * The other record involved (for duplicates / relationships).
   */
  relatedId?: string | null;
  /**
   * What raised it: "import" or "scan".
   */
  source?: string | null;
  status: 'open' | 'acknowledged' | 'resolved';
  updatedAt: string;
  createdAt: string;
}
/**
 * Provider and clinic profile claims awaiting review. Approving a claim promotes the claimant to a provider account and marks the profile claimed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: number;
  claimType: 'provider' | 'clinic';
  /**
   * The provider profile being claimed.
   */
  targetProvider?: (number | null) | Provider;
  /**
   * The clinic profile being claimed.
   */
  targetClinic?: (number | null) | Clinic;
  claimantName: string;
  claimantEmail: string;
  claimantPhone?: string | null;
  /**
   * e.g. Owner, Medical Director, Lead Injector
   */
  roleAtPractice: string;
  /**
   * Required for provider claims.
   */
  licenseNumber?: string | null;
  /**
   * Optional NPI for provider claims.
   */
  npiNumber?: string | null;
  /**
   * Website, LLC docs, or other proof for clinic claims.
   */
  businessProof?: string | null;
  /**
   * Any additional context from the claimant.
   */
  message?: string | null;
  status: 'new' | 'approved' | 'rejected';
  /**
   * Admin who reviewed this claim.
   */
  reviewedBy?: (number | null) | User;
  /**
   * Internal notes visible only to admins.
   */
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter and waitlist subscribers. Only confirmed subscribers receive emails. No health information is stored here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * Optional display name (first name or full).
   */
  name?: string | null;
  /**
   * Double opt-in flow. Only confirmed subscribers receive newsletters.
   */
  status: 'pending' | 'confirmed' | 'unsubscribed';
  source: 'waitlist' | 'quiz' | 'footer' | 'guide' | 'other';
  /**
   * Determines which emails this subscriber receives.
   */
  interestType: 'general' | 'city-waitlist';
  /**
   * City the visitor asked about (city-waitlist only, e.g. "Houston").
   */
  cityTag?: string | null;
  /**
   * Two-letter state code for the city-waitlist interest.
   */
  stateCode?: string | null;
  /**
   * Treatment of interest, if any.
   */
  treatmentTag?: string | null;
  /**
   * UUID used in confirm and unsubscribe links. Never share externally.
   */
  confirmToken?: string | null;
  confirmTokenExpiresAt?: string | null;
  /**
   * When the visitor submitted the signup form.
   */
  optInAt?: string | null;
  /**
   * When the visitor clicked the confirmation link.
   */
  confirmedAt?: string | null;
  /**
   * When the subscriber clicked the unsubscribe link.
   */
  unsubscribedAt?: string | null;
  /**
   * IP address at signup time. Consent audit log only. Not shared.
   */
  ipAtSignup?: string | null;
  /**
   * Set once a go-live email has been sent to this subscriber.
   */
  notified?: boolean | null;
  /**
   * Set when a logged-in patient subscribes.
   */
  linkedUser?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * US ZIP code centroids (GeoNames, public domain). Seeded via `npm run seed:zips`. Read-only reference used for ZIP search resolution and ZIP featuring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zip-codes".
 */
export interface ZipCode {
  id: number;
  /**
   * 5-digit US ZIP code.
   */
  zip: string;
  city: string;
  /**
   * 2-letter state code (e.g. NY).
   */
  state: string;
  county?: string | null;
  /**
   * Latitude of the ZIP centroid.
   */
  lat: number;
  /**
   * Longitude of the ZIP centroid.
   */
  lng: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Video testimonials shown in the "On video" homepage section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-testimonials".
 */
export interface VideoTestimonial {
  id: number;
  /**
   * Short title for the video, e.g. "How to spot an overfilled lip".
   */
  caption: string;
  /**
   * Creator name and credentials, e.g. "Dr. Lena Park, MD".
   */
  creator: string;
  /**
   * Upload the video thumbnail image (9:16 portrait crop, ideally 450×800px).
   */
  thumbnail: number | Media;
  /**
   * Full URL to the video. Examples: https://www.instagram.com/reel/ABC123/ · https://www.tiktok.com/@user/video/123 · https://youtu.be/ABC123
   */
  href: string;
  platform: 'instagram' | 'tiktok' | 'youtube';
  /**
   * Display duration string, e.g. "0:47" or "1:02".
   */
  duration: string;
  /**
   * Show this video on the site.
   */
  active?: boolean | null;
  /**
   * Lower number = shown first.
   */
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Social proof posts shown in the "What they're saying" homepage section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: number;
  platform: 'x' | 'instagram' | 'facebook' | 'reddit' | 'google';
  /**
   * The review or post text (the quote shown on screen).
   */
  quote: string;
  /**
   * Author display name, e.g. "Caroline M.".
   */
  author: string;
  /**
   * Username or handle, e.g. "@carolinem_nyc" or "u/skin_curious".
   */
  handle: string;
  /**
   * Upload the author avatar photo. Leave blank to use a default placeholder.
   */
  avatar?: (number | null) | Media;
  /**
   * Link to the original post. Use # if not applicable.
   */
  href?: string | null;
  /**
   * Display date string, e.g. "Mar 2026".
   */
  date: string;
  /**
   * Like or upvote count. Set to 0 to hide the count.
   */
  likes?: number | null;
  /**
   * Star rating 1–5. Only shown for Google reviews.
   */
  rating?: number | null;
  /**
   * Show as a large featured pull-quote card (always visible, not filterable).
   */
  featured?: boolean | null;
  /**
   * Include in the site social feed.
   */
  active?: boolean | null;
  /**
   * Lower number = shown first.
   */
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'treatments';
        value: number | Treatment;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'clinics';
        value: number | Clinic;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'qa';
        value: number | Qa;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'medical-reviewers';
        value: number | MedicalReviewer;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'before-after-cases';
        value: number | BeforeAfterCase;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'data-alerts';
        value: number | DataAlert;
      } | null)
    | ({
        relationTo: 'claims';
        value: number | Claim;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'zip-codes';
        value: number | ZipCode;
      } | null)
    | ({
        relationTo: 'video-testimonials';
        value: number | VideoTestimonial;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: number | SocialPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  linkedProvider?: T;
  linkedClinic?: T;
  linkedBrand?: T;
  savedProviders?: T;
  savedClinics?: T;
  quizRecommendation?: T;
  setupToken?: T;
  setupTokenExpiry?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments_select".
 */
export interface TreatmentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  tagline?: T;
  shortDescription?: T;
  bodyAreas?: T;
  avgPriceFromUsd?: T;
  avgPriceToUsd?: T;
  priceUnit?: T;
  iconSlug?: T;
  painIndex?: T;
  longevityLabel?: T;
  longevityMonthsMin?: T;
  longevityMonthsMax?: T;
  downtimeLabel?: T;
  downtimeHoursMax?: T;
  guide?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  state?: T;
  parent?: T;
  latitude?: T;
  longitude?: T;
  imageUrl?: T;
  providerCount?: T;
  sortRank?: T;
  featured?: T;
  isLive?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  brandId?: T;
  name?: T;
  slug?: T;
  logoUrl?: T;
  websiteUrl?: T;
  description?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  linkedinUrl?: T;
  subscriptionTier?: T;
  subscriptionStatus?: T;
  claimed?: T;
  claimedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics_select".
 */
export interface ClinicsSelect<T extends boolean = true> {
  clinicId?: T;
  clinicName?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  clinicType?: T;
  brand?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  zip?: T;
  neighborhood?: T;
  county?: T;
  country?: T;
  latitude?: T;
  longitude?: T;
  googlePlaceId?: T;
  googleMapsUrl?: T;
  directionsUrl?: T;
  appleMapsUrl?: T;
  phone?: T;
  email?: T;
  websiteUrl?: T;
  bookingUrl?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  facebookUrl?: T;
  hoursJson?: T;
  serviceType?: T;
  treatmentsOffered?: T;
  offersVirtualConsult?: T;
  acceptsNewPatients?: T;
  startingPrice?: T;
  languages?: T;
  acceptsInsurance?: T;
  paymentMethods?: T;
  amenities?: T;
  logoUrl?: T;
  clinicPhotoUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  photos?: T;
  aggregateRating?: T;
  aggregateRatingCount?: T;
  providers?: T;
  yearEstablished?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  lastScrapedDate?: T;
  importBatch?: T;
  subscriptionTier?: T;
  subscriptionStatus?: T;
  claimed?: T;
  claimedBy?: T;
  status?: T;
  dataConfidence?: T;
  needsManualReview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  providerId?: T;
  fullName?: T;
  slug?: T;
  credentials?: T;
  title?: T;
  yearsExperience?: T;
  yearStartedPracticing?: T;
  clinic?: T;
  additionalClinics?: T;
  boardCertifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  licenseNumber?: T;
  licenseState?: T;
  licenseStatus?: T;
  licenseVerificationUrl?: T;
  npiNumber?: T;
  tagline?: T;
  bio?: T;
  profilePhotoUrl?: T;
  profilePhoto?: T;
  languages?: T;
  gender?: T;
  treatmentsOffered?: T;
  specialties?:
    | T
    | {
        name?: T;
        id?: T;
      };
  pricingBotoxPerUnit?: T;
  pricingFillerPerSyringe?: T;
  pricingConsultation?: T;
  startingPrice?: T;
  loyaltyPrograms?: T;
  acceptsNewPatients?: T;
  offersVirtualConsult?: T;
  offersInPerson?: T;
  websiteUrl?: T;
  email?: T;
  phoneDirect?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  linkedinUrl?: T;
  aggregateRating?: T;
  aggregateRatingCount?: T;
  editorsPick?: T;
  featuredRank?: T;
  subscriptionTier?: T;
  subscriptionStatus?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  lastScrapedDate?: T;
  importBatch?: T;
  claimed?: T;
  claimedBy?: T;
  status?: T;
  profileViewCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewId?: T;
  provider?: T;
  clinic?: T;
  reviewerFirstName?: T;
  reviewerInitial?: T;
  reviewerAgeRange?: T;
  reviewerCity?: T;
  rating?: T;
  reviewTitle?: T;
  reviewText?: T;
  treatmentTag?: T;
  reviewDate?: T;
  sourcePlatform?: T;
  sourceUrl?: T;
  responseFromProvider?: T;
  responseDate?: T;
  verified?: T;
  featured?: T;
  moderationStatus?: T;
  submittedByUser?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  photoId?: T;
  provider?: T;
  clinic?: T;
  treatmentTag?: T;
  photoUrl?: T;
  type?: T;
  pairId?: T;
  weeksPostTreatment?: T;
  caption?: T;
  consentDocumented?: T;
  sourcePlatform?: T;
  sourceUrl?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qa_select".
 */
export interface QaSelect<T extends boolean = true> {
  qaId?: T;
  slug?: T;
  status?: T;
  questionTitle?: T;
  questionText?: T;
  answeredByProvider?: T;
  answeredByName?: T;
  answerText?: T;
  treatmentTag?: T;
  cityTag?: T;
  sourcePlatform?: T;
  sourceUrl?: T;
  date?: T;
  submitterEmail?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photoUrl?: T;
  linkedinUrl?: T;
  twitterUrl?: T;
  articleCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-reviewers_select".
 */
export interface MedicalReviewersSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  credentials?: T;
  title?: T;
  city?: T;
  state?: T;
  bio?: T;
  photoUrl?: T;
  npiNumber?: T;
  boardCertifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  linkedProvider?: T;
  linkedinUrl?: T;
  reviewedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lede?: T;
  excerpt?: T;
  coverImage?: T;
  coverImageUrl?: T;
  category?: T;
  relatedTreatment?: T;
  readTimeMin?: T;
  sourcesCount?: T;
  author?: T;
  medicalReviewer?: T;
  lastMedicallyReviewed?: T;
  body?: T;
  answerSnippet?: T;
  atAGlance?: T;
  faq?: T;
  sources?: T;
  faqs?: T;
  featured?: T;
  publishedAt?: T;
  reviewStatus?: T;
  indexState?: T;
  nofollow?: T;
  importBatch?: T;
  approvedAt?: T;
  approvedBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  coverImageUrl?: T;
  body?: T;
  answerSnippet?: T;
  atAGlance?: T;
  faq?: T;
  sources?: T;
  category?: T;
  author?: T;
  medicalReviewer?: T;
  publishedAt?: T;
  relatedTreatment?: T;
  status?: T;
  featured?: T;
  reviewStatus?: T;
  indexState?: T;
  nofollow?: T;
  importBatch?: T;
  approvedAt?: T;
  approvedBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  treatmentTag?: T;
  cityTag?: T;
  relatedGuide?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after-cases_select".
 */
export interface BeforeAfterCasesSelect<T extends boolean = true> {
  caseTitle?: T;
  beforePhotoUrl?: T;
  afterPhotoUrl?: T;
  treatmentTag?: T;
  weeksPost?: T;
  provider?: T;
  city?: T;
  state?: T;
  patientNote?: T;
  consentGranted?: T;
  featured?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  patientName?: T;
  patientEmail?: T;
  patientPhone?: T;
  provider?: T;
  clinic?: T;
  treatment?: T;
  treatmentTag?: T;
  preferredDate?: T;
  preferredTime?: T;
  message?: T;
  consentToContact?: T;
  status?: T;
  source?: T;
  utm?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  placement?: T;
  scope?: T;
  treatment?: T;
  state?: T;
  city?: T;
  provider?: T;
  clinic?: T;
  bannerImage?: T;
  bannerLinkUrl?: T;
  bannerAltText?: T;
  featuredRank?: T;
  startDate?: T;
  endDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  documentTitle?: T;
  userEmail?: T;
  userId?: T;
  summary?: T;
  changedFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-alerts_select".
 */
export interface DataAlertsSelect<T extends boolean = true> {
  alertKey?: T;
  type?: T;
  severity?: T;
  message?: T;
  collectionSlug?: T;
  documentId?: T;
  relatedId?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  claimType?: T;
  targetProvider?: T;
  targetClinic?: T;
  claimantName?: T;
  claimantEmail?: T;
  claimantPhone?: T;
  roleAtPractice?: T;
  licenseNumber?: T;
  npiNumber?: T;
  businessProof?: T;
  message?: T;
  status?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  status?: T;
  source?: T;
  interestType?: T;
  cityTag?: T;
  stateCode?: T;
  treatmentTag?: T;
  confirmToken?: T;
  confirmTokenExpiresAt?: T;
  optInAt?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  ipAtSignup?: T;
  notified?: T;
  linkedUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zip-codes_select".
 */
export interface ZipCodesSelect<T extends boolean = true> {
  zip?: T;
  city?: T;
  state?: T;
  county?: T;
  lat?: T;
  lng?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-testimonials_select".
 */
export interface VideoTestimonialsSelect<T extends boolean = true> {
  caption?: T;
  creator?: T;
  thumbnail?: T;
  href?: T;
  platform?: T;
  duration?: T;
  active?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  platform?: T;
  quote?: T;
  author?: T;
  handle?: T;
  avatar?: T;
  href?: T;
  date?: T;
  likes?: T;
  rating?: T;
  featured?: T;
  active?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}