/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    treatments: Treatment;
    locations: Location;
    clinics: Clinic;
    providers: Provider;
    reviews: Review;
    photos: Photo;
    qa: Qa;
    authors: Author;
    'medical-reviewers': MedicalReviewer;
    guides: Guide;
    faqs: Faq;
    'before-after-cases': BeforeAfterCase;
    bookings: Booking;
    promotions: Promotion;
    'audit-logs': AuditLog;
    'data-alerts': DataAlert;
    claims: Claim;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    treatments: TreatmentsSelect<false> | TreatmentsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    clinics: ClinicsSelect<false> | ClinicsSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    qa: QaSelect<false> | QaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'medical-reviewers': MedicalReviewersSelect<false> | MedicalReviewersSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'before-after-cases': BeforeAfterCasesSelect<false> | BeforeAfterCasesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'data-alerts': DataAlertsSelect<false> | DataAlertsSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor' | 'provider' | 'patient') | null;
  /**
   * Set on claim approval. The provider profile this user can edit.
   */
  linkedProvider?: (number | null) | Provider;
  /**
   * Set on claim approval. The clinic profile this user can edit.
   */
  linkedClinic?: (number | null) | Clinic;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  providerId: string;
  fullName: string;
  slug: string;
  credentials: 'MD' | 'DO' | 'NP' | 'PA' | 'RN' | 'DDS';
  title: string;
  boardCertifications?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  licenseNumber: string;
  licenseState: string;
  licenseStatus: 'Active' | 'Inactive' | 'Expired';
  licenseVerificationUrl: string;
  npiNumber?: string | null;
  yearsExperience?: number | null;
  yearStartedPracticing?: number | null;
  clinic: number | Clinic;
  tagline?: string | null;
  bio?: string | null;
  profilePhotoUrl?: string | null;
  languages?:
    | (
        | 'English'
        | 'Spanish'
        | 'Mandarin'
        | 'Korean'
        | 'Hindi'
        | 'Russian'
        | 'French'
        | 'Portuguese'
        | 'Arabic'
        | 'Vietnamese'
      )[]
    | null;
  gender?: ('Female' | 'Male' | 'Non-binary' | 'Unknown') | null;
  treatmentsOffered: (number | Treatment)[];
  specialties?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  pricingBotoxPerUnit?: number | null;
  pricingFillerPerSyringe?: number | null;
  pricingConsultation?: number | null;
  /**
   * Display price on cards.
   */
  startingPrice?: number | null;
  acceptsNewPatients?: boolean | null;
  offersVirtualConsult?: boolean | null;
  offersInPerson?: boolean | null;
  websiteUrl?: string | null;
  email?: string | null;
  phoneDirect?: string | null;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  linkedinUrl?: string | null;
  aggregateRating?: number | null;
  aggregateRatingCount?: number | null;
  /**
   * Show "Editor's Pick" ribbon on homepage.
   */
  editorsPick?: boolean | null;
  featuredRank?: number | null;
  sourceUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  lastScrapedDate?: string | null;
  /**
   * Set automatically when a claim is approved.
   */
  claimed?: boolean | null;
  /**
   * The user who claimed this profile.
   */
  claimedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics".
 */
export interface Clinic {
  id: number;
  clinicId: string;
  clinicName: string;
  slug: string;
  tagline?: string | null;
  description?: string | null;
  addressLine1: string;
  addressLine2?: string | null;
  city: string;
  state: string;
  zip: string;
  neighborhood?: string | null;
  county?: string | null;
  country: string;
  latitude: number;
  longitude: number;
  googlePlaceId?: string | null;
  googleMapsUrl?: string | null;
  directionsUrl?: string | null;
  appleMapsUrl?: string | null;
  phone: string;
  email?: string | null;
  websiteUrl: string;
  bookingUrl?: string | null;
  hoursJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  serviceType: 'In-Person' | 'Telehealth' | 'Both';
  acceptsInsurance?: boolean | null;
  /**
   * Semicolon list.
   */
  paymentMethods?: string | null;
  /**
   * Semicolon list.
   */
  amenities?: string | null;
  logoUrl?: string | null;
  clinicPhotoUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  aggregateRating?: number | null;
  aggregateRatingCount?: number | null;
  providers?: (number | Provider)[] | null;
  yearEstablished?: number | null;
  sourceUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  lastScrapedDate?: string | null;
  /**
   * Set automatically when a claim is approved.
   */
  claimed?: boolean | null;
  /**
   * The user who claimed this profile.
   */
  claimedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments".
 */
export interface Treatment {
  id: number;
  name: string;
  slug: string;
  category: 'neurotoxin' | 'filler' | 'biostimulator' | 'skin' | 'thread' | 'body' | 'other';
  tagline?: string | null;
  shortDescription?: string | null;
  bodyAreas?:
    | (
        | 'forehead'
        | 'brow'
        | 'under-eye'
        | 'crows-feet'
        | 'cheeks'
        | 'lips'
        | 'chin'
        | 'jawline'
        | 'neck'
        | 'decolletage'
      )[]
    | null;
  avgPriceFromUsd?: number | null;
  avgPriceToUsd?: number | null;
  priceUnit?: ('per_unit' | 'per_session' | 'per_syringe') | null;
  /**
   * Phosphor icon slug.
   */
  iconSlug?: string | null;
  /**
   * Pillar guide for this treatment.
   */
  guide?: (number | null) | Guide;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  slug: string;
  /**
   * Hero subhead, 1 to 2 sentences.
   */
  lede: string;
  /**
   * Short summary for listing cards and search snippets (under 200 characters). Also used as the default meta description.
   */
  excerpt?: string | null;
  /**
   * Upload the cover image directly. Drag and drop a file or pick from the media library.
   */
  coverImage?: (number | null) | Media;
  /**
   * Legacy / external cover image URL. Used only if no cover image is uploaded above.
   */
  coverImageUrl?: string | null;
  category: 'treatment-guide' | 'article' | 'expert-qa' | 'cost-report';
  relatedTreatment?: (number | null) | Treatment;
  readTimeMin?: number | null;
  sourcesCount?: number | null;
  author: number | Author;
  medicalReviewer?: (number | null) | MedicalReviewer;
  lastMedicallyReviewed?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqs?: (number | Faq)[] | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload images here. Drag and drop, or click to browse.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Required.
   */
  alt: string;
  /**
   * Optional caption shown beneath the image in articles.
   */
  caption?: string | null;
  /**
   * Optional photo credit or source attribution.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  fullName: string;
  slug: string;
  role?: string | null;
  bio?: string | null;
  photoUrl?: string | null;
  linkedinUrl?: string | null;
  twitterUrl?: string | null;
  articleCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-reviewers".
 */
export interface MedicalReviewer {
  id: number;
  fullName: string;
  slug: string;
  credentials: 'MD' | 'DO' | 'NP' | 'PA' | 'RN' | 'DDS' | 'PhD';
  title: string;
  city?: string | null;
  state?: string | null;
  bio?: string | null;
  photoUrl?: string | null;
  npiNumber?: string | null;
  boardCertifications?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Link to provider record if they also see patients.
   */
  linkedProvider?: (number | null) | Provider;
  linkedinUrl?: string | null;
  reviewedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * 40 to 80 words ideal for AEO snippets.
   */
  answer: string;
  scope: 'homepage' | 'treatment' | 'city' | 'guide';
  treatmentTag?: string | null;
  cityTag?: string | null;
  /**
   * "Read the full guide" link target.
   */
  relatedGuide?: (number | null) | Guide;
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  kind: 'country' | 'state' | 'metro' | 'city' | 'neighborhood';
  /**
   * 2-letter state code.
   */
  state?: string | null;
  parent?: (number | null) | Location;
  latitude?: number | null;
  longitude?: number | null;
  imageUrl?: string | null;
  providerCount?: number | null;
  sortRank?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  reviewId: string;
  provider?: (number | null) | Provider;
  clinic: number | Clinic;
  reviewerFirstName?: string | null;
  reviewerInitial?: string | null;
  reviewerAgeRange?: string | null;
  reviewerCity?: string | null;
  rating: number;
  reviewTitle?: string | null;
  reviewText: string;
  treatmentTag?: string | null;
  reviewDate: string;
  sourcePlatform: 'google' | 'yelp' | 'healthgrades' | 'vitals' | 'zocdoc' | 'clinic_site' | 'injectors_world';
  sourceUrl: string;
  responseFromProvider?: string | null;
  responseDate?: string | null;
  verified?: boolean | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  photoId: string;
  provider?: (number | null) | Provider;
  clinic?: (number | null) | Clinic;
  treatmentTag?: string | null;
  photoUrl: string;
  type:
    | 'before'
    | 'after'
    | 'headshot'
    | 'clinic_interior'
    | 'clinic_exterior'
    | 'treatment_room'
    | 'team'
    | 'equipment';
  /**
   * Same id on a before + after pair.
   */
  pairId?: string | null;
  weeksPostTreatment?: number | null;
  caption?: string | null;
  consentDocumented?: boolean | null;
  sourcePlatform: 'clinic_site' | 'google' | 'instagram' | 'injectors_world';
  sourceUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qa".
 */
export interface Qa {
  id: number;
  qaId: string;
  questionTitle: string;
  questionText?: string | null;
  answeredByProvider?: (number | null) | Provider;
  /**
   * Use when provider not in our DB.
   */
  answeredByName?: string | null;
  answerText: string;
  treatmentTag?: string | null;
  cityTag?: string | null;
  sourcePlatform: 'clinic_blog' | 'forum' | 'directory' | 'injectors_world';
  sourceUrl: string;
  date?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after-cases".
 */
export interface BeforeAfterCase {
  id: number;
  caseTitle: string;
  beforePhotoUrl: string;
  afterPhotoUrl: string;
  /**
   * Botox, Lip Filler, etc.
   */
  treatmentTag: string;
  /**
   * Weeks between before and after.
   */
  weeksPost: number;
  provider?: (number | null) | Provider;
  city?: string | null;
  state?: string | null;
  patientNote?: string | null;
  consentGranted: boolean;
  featured?: boolean | null;
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  patientName: string;
  patientEmail: string;
  patientPhone?: string | null;
  provider?: (number | null) | Provider;
  clinic?: (number | null) | Clinic;
  treatment?: (number | null) | Treatment;
  treatmentTag?: string | null;
  preferredDate?: string | null;
  preferredTime?: string | null;
  message?: string | null;
  consentToContact: boolean;
  status: 'new' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  source?: ('website' | 'hero_search' | 'provider_profile' | 'guide_cta' | 'lead_form') | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes by editors.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sponsored slots. Max 3 active per scope, each with a unique rank. The system blocks a 4th slot or a duplicate rank to prevent overselling.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  /**
   * The provider this paid slot promotes.
   */
  provider: number | Provider;
  /**
   * Where this sponsored slot appears.
   */
  scopeType: 'treatment' | 'state' | 'city' | 'treatment+state' | 'treatment+city' | 'body-area';
  /**
   * Required when scope includes a treatment.
   */
  treatmentScope?: (number | null) | Treatment;
  /**
   * Required when scope includes a state or city.
   */
  locationScope?: (number | null) | Location;
  /**
   * Body area slug (e.g. "forehead"). Required when scope = body-area.
   */
  bodyAreaScope?: string | null;
  /**
   * Slot position 1, 2, or 3. Max 3 sponsored per page.
   */
  rank?: number | null;
  startDate?: string | null;
  /**
   * Auto-expires after this date. Leave blank for no expiry.
   */
  endDate?: string | null;
  active?: boolean | null;
  /**
   * Internal label. E.g. "Botox NYC — Q3 2026 campaign".
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only history of every create, update, and delete on tracked collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete';
  collectionSlug: string;
  documentId?: string | null;
  documentTitle?: string | null;
  /**
   * Who performed the action, or "system" for automated/public writes.
   */
  userEmail?: string | null;
  userId?: string | null;
  summary?: string | null;
  /**
   * Field names that changed (updates only).
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Data integrity and operational alerts. Resolve or acknowledge each one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-alerts".
 */
export interface DataAlert {
  id: number;
  /**
   * Deterministic key so re-scans upsert instead of duplicating.
   */
  alertKey: string;
  type:
    | 'duplicate_clinic'
    | 'duplicate_provider'
    | 'missing_coordinates'
    | 'missing_source'
    | 'unknown_treatment'
    | 'broken_relationship'
    | 'unmatched_city'
    | 'missing_trust_field'
    | 'orphaned_promotion'
    | 'other';
  severity: 'error' | 'warning' | 'info';
  message: string;
  collectionSlug?: string | null;
  /**
   * Business id (e.g. providerId / clinicId) or DB id.
   */
  documentId?: string | null;
  /**
   * The other record involved (for duplicates / relationships).
   */
  relatedId?: string | null;
  /**
   * What raised it: "import" or "scan".
   */
  source?: string | null;
  status: 'open' | 'acknowledged' | 'resolved';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: number;
  claimType: 'provider' | 'clinic';
  /**
   * The provider profile being claimed.
   */
  targetProvider?: (number | null) | Provider;
  /**
   * The clinic profile being claimed.
   */
  targetClinic?: (number | null) | Clinic;
  claimantName: string;
  claimantEmail: string;
  claimantPhone?: string | null;
  /**
   * e.g. Owner, Medical Director, Lead Injector
   */
  roleAtPractice: string;
  /**
   * Required for provider claims.
   */
  licenseNumber?: string | null;
  /**
   * Optional NPI for provider claims.
   */
  npiNumber?: string | null;
  /**
   * Website, LLC docs, or other proof for clinic claims.
   */
  businessProof?: string | null;
  /**
   * Any additional context from the claimant.
   */
  message?: string | null;
  status: 'new' | 'approved' | 'rejected';
  /**
   * Admin who reviewed this claim.
   */
  reviewedBy?: (number | null) | User;
  /**
   * Internal notes visible only to admins.
   */
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'treatments';
        value: number | Treatment;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'clinics';
        value: number | Clinic;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'qa';
        value: number | Qa;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'medical-reviewers';
        value: number | MedicalReviewer;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'before-after-cases';
        value: number | BeforeAfterCase;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'data-alerts';
        value: number | DataAlert;
      } | null)
    | ({
        relationTo: 'claims';
        value: number | Claim;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  linkedProvider?: T;
  linkedClinic?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments_select".
 */
export interface TreatmentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  tagline?: T;
  shortDescription?: T;
  bodyAreas?: T;
  avgPriceFromUsd?: T;
  avgPriceToUsd?: T;
  priceUnit?: T;
  iconSlug?: T;
  guide?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  state?: T;
  parent?: T;
  latitude?: T;
  longitude?: T;
  imageUrl?: T;
  providerCount?: T;
  sortRank?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics_select".
 */
export interface ClinicsSelect<T extends boolean = true> {
  clinicId?: T;
  clinicName?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  zip?: T;
  neighborhood?: T;
  county?: T;
  country?: T;
  latitude?: T;
  longitude?: T;
  googlePlaceId?: T;
  googleMapsUrl?: T;
  directionsUrl?: T;
  appleMapsUrl?: T;
  phone?: T;
  email?: T;
  websiteUrl?: T;
  bookingUrl?: T;
  hoursJson?: T;
  serviceType?: T;
  acceptsInsurance?: T;
  paymentMethods?: T;
  amenities?: T;
  logoUrl?: T;
  clinicPhotoUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  aggregateRating?: T;
  aggregateRatingCount?: T;
  providers?: T;
  yearEstablished?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  lastScrapedDate?: T;
  claimed?: T;
  claimedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  providerId?: T;
  fullName?: T;
  slug?: T;
  credentials?: T;
  title?: T;
  boardCertifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  licenseNumber?: T;
  licenseState?: T;
  licenseStatus?: T;
  licenseVerificationUrl?: T;
  npiNumber?: T;
  yearsExperience?: T;
  yearStartedPracticing?: T;
  clinic?: T;
  tagline?: T;
  bio?: T;
  profilePhotoUrl?: T;
  languages?: T;
  gender?: T;
  treatmentsOffered?: T;
  specialties?:
    | T
    | {
        name?: T;
        id?: T;
      };
  pricingBotoxPerUnit?: T;
  pricingFillerPerSyringe?: T;
  pricingConsultation?: T;
  startingPrice?: T;
  acceptsNewPatients?: T;
  offersVirtualConsult?: T;
  offersInPerson?: T;
  websiteUrl?: T;
  email?: T;
  phoneDirect?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  linkedinUrl?: T;
  aggregateRating?: T;
  aggregateRatingCount?: T;
  editorsPick?: T;
  featuredRank?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  lastScrapedDate?: T;
  claimed?: T;
  claimedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewId?: T;
  provider?: T;
  clinic?: T;
  reviewerFirstName?: T;
  reviewerInitial?: T;
  reviewerAgeRange?: T;
  reviewerCity?: T;
  rating?: T;
  reviewTitle?: T;
  reviewText?: T;
  treatmentTag?: T;
  reviewDate?: T;
  sourcePlatform?: T;
  sourceUrl?: T;
  responseFromProvider?: T;
  responseDate?: T;
  verified?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  photoId?: T;
  provider?: T;
  clinic?: T;
  treatmentTag?: T;
  photoUrl?: T;
  type?: T;
  pairId?: T;
  weeksPostTreatment?: T;
  caption?: T;
  consentDocumented?: T;
  sourcePlatform?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qa_select".
 */
export interface QaSelect<T extends boolean = true> {
  qaId?: T;
  questionTitle?: T;
  questionText?: T;
  answeredByProvider?: T;
  answeredByName?: T;
  answerText?: T;
  treatmentTag?: T;
  cityTag?: T;
  sourcePlatform?: T;
  sourceUrl?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photoUrl?: T;
  linkedinUrl?: T;
  twitterUrl?: T;
  articleCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-reviewers_select".
 */
export interface MedicalReviewersSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  credentials?: T;
  title?: T;
  city?: T;
  state?: T;
  bio?: T;
  photoUrl?: T;
  npiNumber?: T;
  boardCertifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  linkedProvider?: T;
  linkedinUrl?: T;
  reviewedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lede?: T;
  excerpt?: T;
  coverImage?: T;
  coverImageUrl?: T;
  category?: T;
  relatedTreatment?: T;
  readTimeMin?: T;
  sourcesCount?: T;
  author?: T;
  medicalReviewer?: T;
  lastMedicallyReviewed?: T;
  body?: T;
  faqs?: T;
  featured?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  treatmentTag?: T;
  cityTag?: T;
  relatedGuide?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after-cases_select".
 */
export interface BeforeAfterCasesSelect<T extends boolean = true> {
  caseTitle?: T;
  beforePhotoUrl?: T;
  afterPhotoUrl?: T;
  treatmentTag?: T;
  weeksPost?: T;
  provider?: T;
  city?: T;
  state?: T;
  patientNote?: T;
  consentGranted?: T;
  featured?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  patientName?: T;
  patientEmail?: T;
  patientPhone?: T;
  provider?: T;
  clinic?: T;
  treatment?: T;
  treatmentTag?: T;
  preferredDate?: T;
  preferredTime?: T;
  message?: T;
  consentToContact?: T;
  status?: T;
  source?: T;
  utm?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  provider?: T;
  scopeType?: T;
  treatmentScope?: T;
  locationScope?: T;
  bodyAreaScope?: T;
  rank?: T;
  startDate?: T;
  endDate?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  documentTitle?: T;
  userEmail?: T;
  userId?: T;
  summary?: T;
  changedFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-alerts_select".
 */
export interface DataAlertsSelect<T extends boolean = true> {
  alertKey?: T;
  type?: T;
  severity?: T;
  message?: T;
  collectionSlug?: T;
  documentId?: T;
  relatedId?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  claimType?: T;
  targetProvider?: T;
  targetClinic?: T;
  claimantName?: T;
  claimantEmail?: T;
  claimantPhone?: T;
  roleAtPractice?: T;
  licenseNumber?: T;
  npiNumber?: T;
  businessProof?: T;
  message?: T;
  status?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}